# Generated by Django 5.0 on 2023-12-31 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_alter_category_options_alter_category_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryCriteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
    ]
