version: '3'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: django
      POSTGRES_DB: django
      POSTGRES_USER: django
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgres/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  data:

