# Generated by Django 5.0.2 on 2024-02-26 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeesignup',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventtimeslot'),
        ),
        migrations.AddField(
            model_name='volunteeragreement',
            name='volunteer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm.volunteer'),
        ),
        migrations.AddField(
            model_name='volunteersignup',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.volunteeragreement'),
        ),
        migrations.AddField(
            model_name='volunteersignup',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
        migrations.AddField(
            model_name='volunteersignup',
            name='time_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.eventtimeslot'),
        ),
        migrations.AddField(
            model_name='volunteersignup',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.volunteer'),
        ),
    ]
