# Generated by Django 5.0 on 2023-12-31 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteeragreement",
            name="volunteer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="crm.volunteer"
            ),
        ),
    ]
