# Generated by Django 5.0 on 2023-12-31 02:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0003_alter_volunteeragreement_volunteer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendee",
            old_name="sex",
            new_name="birth_gender",
        ),
    ]
