# Generated by Django 5.0 on 2023-12-31 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0005_alter_attendee_birth_gender"),
        ("event", "0002_event_published"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendeesignup",
            name="event",
        ),
        migrations.AlterField(
            model_name="attendeesignup",
            name="time_slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="event.eventtimeslot"
            ),
        ),
    ]
