# Generated by Django 5.0 on 2023-12-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
